language: node_js
node_js:
  - "14"
before_script: 
  - "npm install"
deploy: 
  ithub-token: "$GITHUB_TOKEN == Set in travis-ci.org dashboard, marked secure"
  local-dir: dist/collegues-front
  provider: pages
  skip-cleanup: true
  true: 
    branch: master
language: node_js
node_js: 
  - "12"
notifications: 
  email: false
script: "npm run build"