language: node_js
node_js:
  - "14"
before_script:
  - "npm install"
deploy:
  api_key: $GITHUB_TOKEN
  local-dir: dist/collegues-front
  provider: pages
  skip-cleanup: true
  true:
    branch: main
language: node_js
node_js:
  - "14"
notifications:
  email: false
script: "npm run build"
